name: Push to ECR Public

on:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t public.ecr.aws/z4e7u8c6/<YOUR_IMAGE_NAME>:latest .
          docker push public.ecr.aws/z4e7u8c6/<YOUR_IMAGE_NAME>:latest
